// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKPmT7aN7jk_ApTPO_gQWdAdOhQNwoHWM',
    appId: '1:485699311446:web:5374b7494d6ffafd42a8f7',
    messagingSenderId: '485699311446',
    projectId: 'shop-9b0e5',
    authDomain: 'shop-9b0e5.firebaseapp.com',
    databaseURL: 'https://shop-9b0e5-default-rtdb.firebaseio.com',
    storageBucket: 'shop-9b0e5.appspot.com',
    measurementId: 'G-0PQHRZFJ9S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS713ALEhLjBAeK07FYU00L1Lm9FSq2_M',
    appId: '1:485699311446:android:4d5223a52bda28ba42a8f7',
    messagingSenderId: '485699311446',
    projectId: 'shop-9b0e5',
    databaseURL: 'https://shop-9b0e5-default-rtdb.firebaseio.com',
    storageBucket: 'shop-9b0e5.appspot.com',
  );
}
